[theme]
base = "dark"
primaryColor = "#E31837"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
headless = true
